services:
  postgres:
    image: postgres:17
    container_name: medimap-postgres

    environment:
      POSTGRES_DB: medimap
      POSTGRES_USER: medimap
      POSTGRES_PASSWORD: medimap

    ports:
      - "5432:5432"

    volumes:
      - medimap_postgres_data:/var/lib/postgresql/data

volumes:
  medimap_postgres_data: